name: Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    environment: production
    env:
      MONGO_ROOT_USERNAME: ${{ secrets.MONGO_ROOT_USERNAME }}
      MONGO_ROOT_PASSWORD: ${{ secrets.MONGO_ROOT_PASSWORD }}
      MONGODB_DB_NAME: ${{ secrets.MONGODB_DB_NAME }}
      WEB_ANGULAR_ORIGIN: ${{ secrets.WEB_ANGULAR_ORIGIN }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_DOMAINS: ${{ secrets.CLOUDFLARE_DOMAINS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy edge (Caddy + DDNS) and prod stack
        run: docker compose -f docker-compose.edge.yml -f docker-compose.prod.yml up -d --build

  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: self-hosted
    environment: development
    env:
      MONGO_ROOT_USERNAME: ${{ secrets.MONGO_ROOT_USERNAME }}
      MONGO_ROOT_PASSWORD: ${{ secrets.MONGO_ROOT_PASSWORD }}
      MONGODB_DB_NAME: ${{ secrets.MONGODB_DB_NAME }}
      WEB_ANGULAR_ORIGIN: ${{ secrets.WEB_ANGULAR_ORIGIN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy dev stack
        run: docker compose -f docker-compose.dev.yml up -d --build
